"""
Blueprint: dynamic.

Renders a template based on the routes in the settings.
"""
from flask import render_template, current_app, redirect, abort, request
from . import dynamic
from brmflask.utils.routing import route_exists, site_path
from brmflask.utils.minify import minify_response
from brmflask.utils.cache import cache
# from brmflask.utils.analytics import record
# from brmflask.utils.log import log


@dynamic.route('/')
@cache.cached()
@minify_response
def homepage():
    """Render the Homepage."""
    return render_template(
        site_path('home.html')
    )


# record requests
# @analytics.record()
@dynamic.route('/<path:path>', methods=['GET'])
@cache.cached()
@minify_response
def router(path):
    """
    Render the template at path.

    Dynamically routes to all routes generated by the setting ROUTES.
    If an route cannot be found, a 404 is thrown.

    :param path: <string> path
    :return: render_template object
    """
    route = route_exists(path)
    if route:
        return render_template(
            site_path(route)
        )
    else:
        abort(404)


@dynamic.before_request
def before_request():
    """Redirect if path is found in config.['REDIRECT_KEYS']."""
    path = request.path[1:]
    if path in current_app.config['REDIRECT_KEYS']:
        return redirect(
            current_app.config['REDIRECTS'].get(path),
            code=301
        )
